name: task_list_app
description: Task list application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter_localizations: # Localization support
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  get_storage: ^2.1.1 
  flutter:
    sdk: flutter
  go_router: ^8.0.3
  url_strategy: ^0.2.0
  equatable: ^2.0.5
  intl: ^0.18.0
  flutter_screenutil: ^5.8.1
  shared_preferences: ^2.1.2
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - languages/